# I followed this tutorial here: https://www.freecodecamp.org/news/a-beginners-guide-to-docker-how-to-create-your-first-docker-application-cc03de9b639f/
# And made modifications to best suit my own purposes

# Setup using ubuntu image.
FROM fedora:latest

# Create a user working directory.
WORKDIR /tmp

# Install tools.
RUN dnf install -y neofetch
RUN dnf install -y nano
RUN dnf install -y vim

